"""
HDF5 converter for faster reads while preserving compatibility.

This script scans an input directory for files generated by
exp/shapenet/preprocess.py (sn_*_mesh.hdf5 and sn_*_samples_evecs.hdf5),
then rewrites them to an output directory with optimized compression and
chunking settings.

Defaults are tuned for environments where CPU is the bottleneck (shared
server, limited cores) but disk and memory are abundant:
- target compression: none
- rechunk samples/evecs/mass for contiguous per-sample reads

All file/group/dataset attrs are preserved, and dataset names, shapes,
and dtypes remain unchanged. Optional ragged outputs (verts_data/verts_offsets
and faces_data/faces_offsets) can be produced for verts/faces to enable
faster random access without breaking compatibility.

Usage:
    python -m exp.cvt_h5 --input-dir /path/to/src --output-dir /path/to/dst

"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Any, Optional, Tuple

import h5py
import numpy as np


def parse_args() -> argparse.Namespace:
    """Parse command line arguments for the HDF5 conversion script."""
    parser = argparse.ArgumentParser("Convert preprocessed HDF5 to faster-read layout")
    parser.add_argument("--input-dir", type=str, required=True, help="Source directory containing HDF5 files")
    parser.add_argument("--output-dir", type=str, required=True, help="Destination directory for converted HDF5 files")
    parser.add_argument(
        "--target-compression",
        type=str,
        default="none",
        choices=["none", "lzf", "gzip"],
        help="Target compression filter",
    )
    parser.add_argument(
        "--target-compression-opts",
        type=int,
        default=4,
        help="Compression options (e.g., gzip level); ignored for non-gzip",
    )
    parser.add_argument(
        "--rechunk-samples",
        action="store_true",
        default=True,
        help="Rechunk samples/evecs/mass datasets for faster per-sample reads",
    )
    parser.add_argument(
        "--ragged",
        action="store_true",
        default=False,
        help="Additionally write verts_data/verts_offsets and faces_data/faces_offsets",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=16,
        help="Concurrent workers (processes) for file-level conversion",
    )
    return parser.parse_args()


def _compression_args(target_compression: str, target_compression_opts: Optional[int]) -> Tuple[Optional[str], Optional[int]]:
    """Map user compression settings to h5py create_dataset args."""
    if target_compression == "none":
        return None, None
    if target_compression == "gzip":
        return "gzip", target_compression_opts
    return "lzf", None


def _desired_chunks(name: str, shape: Tuple[int, ...], rechunk_samples: bool) -> Optional[Tuple[int, ...]]:
    """Compute desired chunks for known large arrays; otherwise None to let h5py decide.

    Returns None for datasets that should retain existing chunking.
    """
    if not rechunk_samples:
        return None
    if name == "samples" and len(shape) == 4:
        n_points = int(shape[2])
        channels = int(shape[3])
        return (1, 1, n_points, channels)
    if name == "evecs" and len(shape) == 4:
        n_points = int(shape[2])
        kdim = int(shape[3])
        return (1, 1, n_points, kdim)
    if name == "mass" and len(shape) == 3:
        n_points = int(shape[2])
        return (1, 1, n_points)
    return None


def _copy_attrs(src: h5py.AttributeManager, dst: h5py.AttributeManager) -> None:
    """Copy all attributes key-by-key from src to dst."""
    for key in src.keys():
        try:
            dst[key] = src[key]
        except Exception:
            # TODO: Handle edge cases where attribute types are not directly serializable.
            pass


def _copy_dataset(
    src_ds: h5py.Dataset,
    dst_group: h5py.Group,
    name: str,
    compression: Optional[str],
    compression_opts: Optional[int],
    rechunk_samples: bool,
) -> None:
    """Copy a dataset from src to dst, optionally changing compression and chunks."""
    shape = tuple(int(d) for d in src_ds.shape)
    dtype = src_ds.dtype

    chunks = _desired_chunks(name, shape, rechunk_samples)

    vlen_base = h5py.check_dtype(vlen=dtype)
    if vlen_base is not None:
        dst_ds = dst_group.create_dataset(
            name,
            shape=shape,
            dtype=dtype,
            compression=compression,
            compression_opts=compression_opts,
        )
        # Write row-by-row for variable-length datasets.
        for i in range(shape[0]):
            dst_ds[i] = src_ds[i]
    else:
        data = src_ds[...]
        if chunks is not None:
            dst_ds = dst_group.create_dataset(
                name,
                data=data,
                compression=compression,
                compression_opts=compression_opts,
                chunks=chunks,
            )
        else:
            dst_ds = dst_group.create_dataset(
                name,
                data=data,
                compression=compression,
                compression_opts=compression_opts,
            )

    _copy_attrs(src_ds.attrs, dst_ds.attrs)


def _copy_group(
    src_grp: h5py.Group,
    dst_grp: h5py.Group,
    compression: Optional[str],
    compression_opts: Optional[int],
    rechunk_samples: bool,
) -> None:
    """Recursively copy groups and datasets, preserving attrs."""
    _copy_attrs(src_grp.attrs, dst_grp.attrs)
    for key in src_grp.keys():
        obj = src_grp[key]
        if isinstance(obj, h5py.Group):
            new_grp = dst_grp.create_group(key)
            _copy_group(obj, new_grp, compression, compression_opts, rechunk_samples)
        elif isinstance(obj, h5py.Dataset):
            _copy_dataset(obj, dst_grp, key, compression, compression_opts, rechunk_samples)


def _add_ragged_parallel(
    src_file: h5py.File,
    dst_file: h5py.File,
) -> None:
    """Optionally add ragged parallel datasets for verts/faces at file root."""
    if "verts" in src_file and "vert_shapes" in src_file:
        verts = [np.asarray(src_file["verts"][i], dtype=np.float32) for i in range(len(src_file["verts"]))]
        total = int(sum(v.size for v in verts))
        offsets = np.zeros(len(verts) + 1, dtype=np.int64)
        for i in range(len(verts)):
            offsets[i + 1] = offsets[i] + verts[i].size
        dst_file.create_dataset("verts_data", data=np.concatenate(verts, axis=0).astype(np.float32))
        dst_file.create_dataset("verts_offsets", data=offsets)

    if "faces" in src_file and "face_shapes" in src_file:
        faces = [np.asarray(src_file["faces"][i], dtype=np.int32) for i in range(len(src_file["faces"]))]
        total = int(sum(f.size for f in faces))
        offsets = np.zeros(len(faces) + 1, dtype=np.int64)
        for i in range(len(faces)):
            offsets[i + 1] = offsets[i] + faces[i].size
        dst_file.create_dataset("faces_data", data=np.concatenate(faces, axis=0).astype(np.int32))
        dst_file.create_dataset("faces_offsets", data=offsets)


def convert_one_file(
    src_path: Path,
    dst_path: Path,
    target_compression: str,
    target_compression_opts: Optional[int],
    rechunk_samples: bool,
    ragged: bool,
) -> None:
    """Convert a single HDF5 file according to the provided options."""
    compression, comp_opts = _compression_args(target_compression, target_compression_opts)

    with h5py.File(src_path, "r") as src:
        with h5py.File(dst_path, "w") as dst:
            _copy_attrs(src.attrs, dst.attrs)
            _copy_group(src, dst, compression, comp_opts, rechunk_samples)
            if ragged:
                _add_ragged_parallel(src, dst)

    # Print a short summary for verification.
    with h5py.File(dst_path, "r") as hf:
        print(f"Converted: {dst_path.name}")
        for key in hf.keys():
            obj = hf[key]
            if isinstance(obj, h5py.Dataset):
                print(
                    f"  ds={key} shape={obj.shape} dtype={obj.dtype} chunks={obj.chunks} comp={obj.compression}"
                )
        print(f"  file_attrs={list(hf.attrs.keys())}")


def main() -> None:
    """Entry point: scan input dir, convert files with concurrency."""
    args = parse_args()
    in_dir = Path(args.input_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    mesh_files = sorted(in_dir.glob("*_mesh.hdf5"))
    samples_files = sorted(in_dir.glob("*_samples_evecs.hdf5"))
    all_files = mesh_files + samples_files
    if not all_files:
        raise FileNotFoundError("No *_mesh.hdf5 or *_samples_evecs.hdf5 files found in input-dir")

    tasks = []
    for src in all_files:
        dst = out_dir / src.name
        tasks.append((src, dst))

    # Simple concurrency per file using multiprocessing; safe as each process handles distinct files.
    # TODO: On systems with strict I/O constraints, consider rate-limiting concurrent writes.
    from concurrent.futures import ProcessPoolExecutor, as_completed

    with ProcessPoolExecutor(max_workers=int(args.workers)) as ex:
        futs = []
        for src, dst in tasks:
            futs.append(
                ex.submit(
                    convert_one_file,
                    src,
                    dst,
                    args.target_compression,
                    args.target_compression_opts,
                    args.rechunk_samples,
                    args.ragged,
                )
            )
        for fut in as_completed(futs):
            try:
                fut.result()
            except Exception as e:
                print(f"Conversion error: {e}")


if __name__ == "__main__":
    main()
